### ISSUE TITLE
Keep this project in root directory

### ISSUE THREAD

**Issue by Shahed-Chy-Suzan** [nazim725/Nazim-s-Portfolio#1]
Keep this project in root directory.
for example:
nazim725/Nazim-s-Portfolio/projectFiles
not like: nazim725/Nazim-s-Portfolio/portfolio website/projectFiles

**Comment by nazim725** [comment]
Akn thik ahce na???

**Comment by Shahed-Chy-Suzan** [comment]
Shera..

**Comment by nazim725** [comment]
Ummmmmmmahhh
